### ISSUE TITLE
Identify sources

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/northeuralex#1]
@LinguList says " sources: since to my knowledge there's no link from source to language, we're left alone and cannot tell which one belongs to which source. We could ask Johannes on some of these points"

**Comment by xrotwang** [comment]
Johannes told me they are working on this for the next version.

**Comment by SimonGreenhill** [comment]
There's no obvious way to do this at the moment as there's no obvious linking of lexemes to sources or languages to sources on the current website.

**Comment by SimonGreenhill** [comment]
closing this as it sounds like it's a problem upstream
