### ISSUE TITLE
Diphthongs transcribed as sequences of simple vowels for Manchu (and others)

### ISSUE THREAD

**Issue by justeuer** [lexibank/northeuralex#11]
The problem seems to be present in many languages. For some (as Japanese) I would not expect to find diphthongs, but for Manchu and English this is surely inadequate. This code snippet shows all languages that don't have `diphthong`s in their forms:

```python
from cltoolkit import Wordlist
from lexibank_northeuralex import Dataset as NorthEuraLex
from pycldf import Dataset
from pyclts import CLTS

clts = CLTS()
bipa = clts.bipa

word_list = Wordlist([Dataset.from_metadata(NorthEuraLex().cldf_dir.joinpath('cldf-metadata.json'))])

for i, language in enumerate(word_list.languages):
    sound_types = []
    for form in language.forms:
        segments = form.data["Segments"]
        for segment in segments:
            sound_type = bipa[segment].type
            sound_types.append(sound_type)
    print("{} {}\t{}\t{}".format(i+1, language.id.split('-')[1], 'diphthong' in sound_types, language.name))

```

Partial output:

```
52 eng  False   English
75 mnc  False   Manchu
```

**Comment by LinguList** [comment]
To handle this, orthography profiles need to be adjusted. In this repository, the original data coding was not segmenting data at all, but rather left even diacritics unsegmented. If we can pull out a list of possible diphtongs from the current data (easy to do, right?), we can adjust the profiles accordingly.

**Comment by LinguList** [comment]
So the solution is to really change the orthography profile in `etc/orthography.tsv`.

**Comment by justeuer** [comment]
Good, that would mean that the raw diphthongs should be in the "Grapheme" column and the result of the segmentation in the "IPA" column?
```
Grapheme   IPA
ai         ai
```

**Comment by LinguList** [comment]
Yep, exactly. You could even add a language-specific profile into a 
folder "etc/orthography/English.tsv" (provided English is our 
langauge_ID. But for now, it may just be sufficient to add this there, 
right? If you can do so, would you modify the profile and then run this 
code (use a fresh venv, so we have only the current requirements):

cldfbench lexibank.makecldf --clts-version-v2.1.0 
--glottolog-version=v4.4 --concepticon-version=v2.5.0 
lexibank_northeuralex.py

This will recreate the data with the newly merged data points.

**Comment by LinguList** [comment]
Ah, and if you make a PR, I can check this directly.

**Comment by justeuer** [comment]
I tried to do this in a systematic way (can't attach it unfortunately):

```python
from cltoolkit import Wordlist
from lexibank_northeuralex import Dataset as NorthEuraLex
from pathlib import Path
from pyclts import CLTS
from pycldf import Dataset

clts = CLTS()
bipa = clts.bipa


# load orthography
orth_file = Path("etc/orthography.tsv").open('r').readlines()[1:]

diphthongs = []

for line in orth_file:
    grapheme, ipa = line.split("\t")
    sound = bipa[grapheme]
    if sound.type == 'diphthong':
        diphthongs.append(sound.grapheme)
diphthongs = set(diphthongs)


# find possible diphthong
word_list = Wordlist([Dataset.from_metadata(NorthEuraLex().cldf_dir.joinpath('cldf-metadata.json'))])

diphthong_candidates = []
for i, language in enumerate(word_list.languages):
    for form in language.forms:
        segments = form.data["Segments"]
        for i in range(1,len(segments)-1):
            s1 = bipa[segments[i]]
            s2 = bipa[segments[i+1]]
            if s1.type == 'vowel' and s2.type == 'vowel':
                if not \
                (
                    # identical sounds don't form a diphthong
                    s1.grapheme == s2.grapheme or
                    # also not if they only differ in length
                    set(s1.name.split()).difference(set(s2.name.split())) == 'long' or
                    set(s1.name.split()).difference(set(s2.name.split())) == 'half-long' or
                    set(s2.name.split()).difference(set(s1.name.split())) == 'long' or
                    set(s2.name.split()).difference(set(s1.name.split())) == 'half-long' or
                    # exclude sequences of long vowels
                    (s1.duration == 'long' and s2.duration == 'long') or 
                    # exclude nasal vowels
                    s1.nasalization or s2.nasalization or
                    # exclude glottalized vowels
                    s1.glottalization or s2.glottalization or
                    # and pharyngealized vowels
                    s1.pharyngealization or s2.pharyngealization
                ):
                    diphthong_candidates.append(s1.grapheme+s2.grapheme)

# find diphthongs not yet in orthography.tsv
diphthong_candidates = set(diphthong_candidates)
diphthong_candidates = diphthong_candidates.difference(diphthongs)

for d in diphthong_candidates:
    print("{}\t{}".format(d,d))
```

Appending the output of this script  to `etc/orthography.csv` "solves" the diphthong problem, but leaves undesired traces in the forms (after making the dataset):

```
'm', 'iɛ', '<<̯>>', 'tː', 'iæ'
```
It is relatively opaque to me how the `<<̯>>` comes there. Is it a subscript that originally belonged to the diphthong?

Otherwise, if you are happy with the list of diphthongs the script provides, I can prepare a pull request.

**Comment by LinguList** [comment]
It is not surprising if you have worked hands-on with transcriptions by people. This shows that these specific cases also need to be handled. It is a part of the diphthong, but I'd ignore it and convert it to iE without the diacritic.

**Comment by LinguList** [comment]
You can check with `cldfbench lexibank.check_profile lexibank_northeuralex.py` what is left and problematic.

**Comment by LinguList** [comment]
It would be good to see how many of these cases we have. The output of the specific command I mentioned above will help here.

**Comment by justeuer** [comment]
For now I simply extracted the diphthongs from the raw graphemes and inserted them with diacritics into orthography.tsv. Now `cldfbench lexibank.check_profile lexibank_northeuralex.py` doesn't show any unrecognized subscripts anymore.

**Comment by justeuer** [comment]
But in most languages diphthongs are not marked with subscripts at all. For these I'll use the the script above.

**Comment by justeuer** [comment]
I don't think this should be merged into master, at least not the ad-hoc part. I can make the dataset with the unambiguous cases (those already in the graphemes) added though.

**Comment by LinguList** [comment]
Please make a PR and let me check it. The reason why we have CLDF is that we want to prevent ad-hoc code on individual datasets, so we are keen on improving data, and if this passes my review, you'll be listed as a contributor for the profile.
