### ISSUE TITLE
correct the orthography profile

### ISSUE THREAD

**Issue by LinguList** [lexibank/northeuralex#4]
The orthography profile is automatic, nobody corrected it manually, but this should be done.

**Comment by tresoldi** [comment]
Finished, down from ~100,000 invalid lexemes to zero. https://github.com/lexibank/northeuralex/commit/958353c2a07661493c439e20851fe78b8b674fc2

I stupidly pushed to master, please let me know of problems so I revert/fix, otherwise we can close this. :smiley:
