### ISSUE TITLE
Invalid segments

### ISSUE THREAD

**Issue by chrzyki** [lexibank/northeuralex#5]
@tresoldi, would you mind having a look those?

| ID | LANGUAGE | CONCEPT | FORM | SEGMENTS |
|:-------------------|:-----------|:-------------|:----------------|:-----------------------------------|
| khk-EssenN-1 | khk | EssenN | ʲite | <s> ^ </s> j i t e |
| khk-GelachterN-1 | khk | GelachterN | ʲinetem | <s> ^ </s> j i n e t e m |
| khk-GriffN-1 | khk | GriffN | ʲiʃ | <s> ^ </s> j i ʃ |
| khk-KanteN-1 | khk | KanteN | ʲirmeɡ | <s> ^ </s> j i r m e g |
| khk-SpeiseN-1 | khk | SpeiseN | ʲite | <s> ^ </s> j i t e |
| khk-StammN-1 | khk | StammN | ʲiʃ | <s> ^ </s> j i ʃ |
| khk-essenV-1 | khk | essenV | ʲitex | <s> ^ </s> j i t e x |
| khk-geratenV-1 | khk | geratenV | ʲiɮrex | <s> ^ </s> j i ɮ r e x |
| khk-glaubenV-1 | khk | glaubenV | ʲitʰɡex | <s> ^ </s> j i tʰ g e x |
| khk-groA-1 | khk | groA | ʲix | <s> ^ </s> j i x |
| khk-kommenV-1 | khk | kommenV | ʲirex | <s> ^ </s> j i r e x |
| khk-lachenV-1 | khk | lachenV | ʲinex | <s> ^ </s> j i n e x |
| khk-pfeifenV-1 | khk | pfeifenV | ʲisɡerex | <s> ^ </s> j i s g e r e x |
| khk-scharfA-2 | khk | scharfA | ʲirtʰej | <s> ^ </s> j i r tʰ e j |
| khk-schickenV-1 | khk | schickenV | ʲiɮɡex | <s> ^ </s> j i ɮ g e x |
| khk-soADV-2 | khk | soADV | ʲinɡet | <s> ^ </s> j i n g e t |
| khk-zunehmenV-1 | khk | zunehmenV | ʲixsex | <s> ^ </s> j i x s e x |
| lit-BuchtN-1 | lit | BuchtN | ʲiːɫɐnkɐ | <s> ^ </s> j iː lˠ ɐ n k ɐ |
| lit-eintretenV-1 | lit | eintretenV | ʲiːʒɛnˑɡtʲɪ | <s> ^ </s> j iː ʒ ɛ nˑ g tʲ ɪ |
| lit-einwickelnV-1 | lit | einwickelnV | ʲiːʋʲiːnʲɪoːtʲɪ | <s> ^ </s> j iː ʋʲ iː nʲ ɪ oː tʲ ɪ |
| lit-hinaufADV-2 | lit | hinaufADV | ʲiː ʋʲɪrˑʃuː | <s> ^ </s> j iː + ʋʲ ɪ rˑ ʃ uː |
| lit-hineingehenV-1 | lit | hineingehenV | ʲiːɛʲɪˑtʲɪ | <s> ^ </s> j iː ɛ j ɪˑ tʲ ɪ |
| lit-steckenV-2 | lit | steckenV | ʲiːkʲɪʃtʲɪ | <s> ^ </s> j iː kʲ ɪ ʃ tʲ ɪ |
| lit-verschiedenA-1 | lit | verschiedenA | ʲiːʋɐʲɪˑrʊs | <s> ^ </s> j iː ʋ ɐ j ɪˑ r ʊ s |

**Comment by LinguList** [comment]
This is strange. What lexibank version do you use? The orthography is missing the `^` and the `$` resolving to `NULL`, but they should not be needed in the new lexibank, but it seems like this is in fact happening...

**Comment by LinguList** [comment]
fixed now, I thought I had pushed my verison, where the ^ is deleted...

**Comment by chrzyki** [comment]
Thanks!
