### ISSUE TITLE
change citation to the most recent paper by Dellert et al. 

### ISSUE THREAD

**Issue by LinguList** [lexibank/northeuralex#8]
https://doi.org/10.1007/s10579-019-09480-6

**Comment by LinguList** [comment]
The title should also be modified, of course.

**Comment by tresoldi** [comment]
I followed what they have in the homepage ("How to cite the dataset: Dellert, J., Daneyko, T., Münch, A. et al. Lang Resources & Evaluation (2019). https://doi.org/10.1007/s10579-019-09480-6 (version 0.9)."), should I then move to "NorthEuraLex: a wide-coverage lexical database of Northern Eurasia"?

The year is a bit strange here: while the link says "Published: 30 November 2019", it gives the official citation as "Language Resources and Evaluation volume 54, pages273–301(2020)".

**Comment by tresoldi** [comment]
This can now be closed, correct?

**Comment by chrzyki** [comment]
Agreed
